baseURL = "https://poems.akhil.me"
languageCode = "en-us"
title = "Poems by Akhil"
summaryLength = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  description = "A collection of poems exploring life, nature, and reflection"
  author = "Akhil"
  favicon = ""

[module]
  [[module.imports]]
    path = "github.com/sergeyklay/gohugo-theme-ed"

