baseURL = "https://poems.akhil.me"
languageCode = "en-us"
title = "Poems by Akhil"
summaryLength = 10

[module]
  [[module.imports]]
    path = "github.com/sergeyklay/gohugo-theme-ed"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  description = "A collection of poems exploring life, nature, and reflection"
  author = "Akhil"
  favicon = ""
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Poems"
    url = "/poems/"
    weight = 2
